spring:
  application:
    name: price-converter
  mvc:
    log-request-details: true
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
#      dev only
      show-details: always
  tracing:
    sampling:
#      dev only, default = 0.1
      probability: 1.0


pl.pbf:
  nbp:
    url: http://api.nbp.pl

